apiVersion: 1
datasources:
  - name: FlowMind Prometheus
    uid: flowmind-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
